### ISSUE TITLE
October 3rd topic voting

### ISSUE THREAD

**Issue by matt0x6F** [dfwsre/docs#1]
Post a reply with a topic you'd like to hear. Topic votes solidify on **September 23rd** and this thread will be **closed**. The largest number of votes wins.

**Preface**
I'd like to try out the idea that anyone can bring material to present as long as it conforms to what the group votes on. This eliminates one person getting up the whole time.

**How to vote**
Throw a thumbs up on a topic you like. Only thumbs up reactions are counted.

**Comment by matt0x6F** [comment]
I propose a mashup first-half session that covers:

* On-call rotations, alert fatigue, and the wheel of pain
* For a demo I can show off my Kubernetes cluster, which I constantly introduce failure in

**Comment by randalllee** [comment]
Don't we want to start to define what SRE is?

**Comment by matt0x6F** [comment]
I figured that would happen asynchronously from the actual talks (ie, it'd be something the community continually works on), but we could definitely focus on that.

Maybe that could be the second half?

**Comment by joshcurago** [comment]
Compensation, Negotiation, and when is it time to find a new role?

**Comment by josharrington** [comment]
Compensation, negotiation, and deciding when it's time to make a move

**Comment by josharrington** [comment]
Containers for the Real World - Beyond the hype, where do containers make sense? Density, Cost Savings, Redundancy, Build Environments, etc

**Comment by josharrington** [comment]
Monitoring and Alerting - A group discussion. There's as many monitoring platforms as there are javascript frameworks, how do we decide? Old monoliths (Opennms, Nagios) vs the new hotness, managing monitoring complexity

**Comment by randalllee** [comment]
Chaos Engineering is always good topic
